name: Build ByteHook Static Library

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # Копируем всё важное в отдельную чистую папку перед загрузкой
    - name: Prepare Artifacts Folder
      run: |
        mkdir -p final_output/libs
        mkdir -p final_output/include
        
        # Находим все файлы .a и копируем их с сохранением структуры папок (архитектур)
        cd bytehook/build
        find . -name "*.a" -exec cp --parents {} ../../final_output/libs/ \;
        cd ../..
        
        # Забираем заголовочный файл для C++
        cp bytehook/src/main/cpp/bytehook.h final_output/include/

    # Загружаем готовую собранную папку
    - name: Upload Static Libraries (.a) and Header (.h)
      uses: actions/upload-artifact@v4
      with:
        name: bytehook-complete-sdk
        path: final_output/

