name: Build ByteHook Static Library

on:
  workflow_dispatch: # Кнопка ручного запуска в Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # Автоматический поиск и сборка файлов по всему репозиторию
    - name: Prepare Artifacts Folder
      run: |
        mkdir -p final_output/libs
        mkdir -p final_output/include
        
        # Умный поиск всех файлов .a и их копирование
        find . -name "*.a" -type f -exec cp --parents {} final_output/libs/ \;
        
        # Умный поиск файла bytehook.h по всему проекту (игнорируя папку финального вывода)
        find . -name "bytehook.h" -type f ! -path "./final_output/*" -exec cp {} final_output/include/ \;
        
        # Проверка, что файлы успешно скопированы
        ls -R final_output/

    # Загрузка архива на GitHub
    - name: Upload Static Libraries (.a) and Header (.h)
      uses: actions/upload-artifact@v4
      with:
        name: bytehook-complete-sdk
        path: final_output/
        
